### ISSUE TITLE
Support PHPStan 2.0

### ISSUE THREAD

**Issue by SchmidtClaudia** [composer/pcre#39]
When running PHPStan 2.0 with composer/pcre 3.3.1 I get the following error (complete stack trace below)

>  PHPStan\Analyser\TypeSpecifier::create(): Argument #4 ($scope) must be of type PHPStan\Analyser\Scope, false given, called in /var/www/html/vendor/composer/pcre/src/PHPStan/PregMatchTypeSpecifyingExtension.php  
>      on line 96 while analysing file /var/www/html/src/SomeFile.php

In PHPStan 2.0 the constructor parameters for TypeSpecifier::create() and SpecifiedTypes  changed see PHPStan Upgrade guides https://github.com/phpstan/phpstan/discussions/11816

If desired I can make a pull request with my local changes to get it running. But I'm not sure how to handle the `overwrite` and `node` properties correctly. 

 ## Stack trace
     #0 /var/www/html/vendor/composer/pcre/src/PHPStan/PregMatchTypeSpecifyingExtension.php(96): PHPStan\Analyser\TypeSpecifier->create(Object(PhpParser\Node\Expr\Variable), Object(PHPStan\Type\Constant\ConstantArrayType),          
     Object(PHPStan\Analyser\TypeSpecifierContext), false, Object(PHPStan\Analyser\MutatingScope), Object(PhpParser\Node\Expr\StaticCall))                                                                                              
     #1 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/TypeSpecifier.php(392): Composer\Pcre\PHPStan\PregMatchTypeSpecifyingExtension->specifyTypes(Object(PHPStan\Reflection\ResolvedMethodReflection),         
     Object(PhpParser\Node\Expr\StaticCall), Object(PHPStan\Analyser\MutatingScope), Object(PHPStan\Analyser\TypeSpecifierContext))                                                                                                     
     #2 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/MutatingScope.php(2845): PHPStan\Analyser\TypeSpecifier->specifyTypesInCondition(Object(PHPStan\Analyser\MutatingScope),                                  
     Object(PhpParser\Node\Expr\StaticCall), Object(PHPStan\Analyser\TypeSpecifierContext))                                                                                                                                             
     #3 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(2874): PHPStan\Analyser\MutatingScope->filterByTruthyValue(Object(PhpParser\Node\Expr\StaticCall))                                  
     #4 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/ExpressionResult.php(70): PHPStan\Analyser\NodeScopeResolver::PHPStan\Analyser\{closure}()                                                                
     #5 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(796): PHPStan\Analyser\ExpressionResult->getTruthyScope()                                                                           
     #6 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(422): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\If_), Object(PHPStan\Analyser\MutatingScope),  
     Object(Closure), Object(PHPStan\Analyser\StatementContext))                                                                                                                                                                        
     #7 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(613): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\ClassMethod), Array,                          
     Object(PHPStan\Analyser\MutatingScope), Object(Closure), Object(PHPStan\Analyser\StatementContext))                                                                                                                                
     #8 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(4512): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\ClassMethod),                                 
     Object(PHPStan\Analyser\MutatingScope), Object(Closure), Object(PHPStan\Analyser\StatementContext))                                                                                                                                
     #9 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(4528): PHPStan\Analyser\NodeScopeResolver->processNodesForCalledMethod(Object(PhpParser\Node\Stmt\Class_), '/var/www/html/s...',    
     Object(PHPStan\Reflection\ResolvedMethodReflection), Object(Closure))                                                                                                                                                              
     #10 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(4524): PHPStan\Analyser\NodeScopeResolver->processNodesForCalledMethod(Array, '/var/www/html/s...',                                
     Object(PHPStan\Reflection\ResolvedMethodReflection), Object(Closure))                                                                                                                                                              
     #11 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(4528): PHPStan\Analyser\NodeScopeResolver->processNodesForCalledMethod(Object(PhpParser\Node\Stmt\Namespace_),                     
     '/var/www/html/s...', Object(PHPStan\Reflection\ResolvedMethodReflection), Object(Closure))                                                                                                                                        
     #12 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(4450): PHPStan\Analyser\NodeScopeResolver->processNodesForCalledMethod(Array, '/var/www/html/s...',                                
     Object(PHPStan\Reflection\ResolvedMethodReflection), Object(Closure))                                                                                                                                                              
     #13 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(2041): PHPStan\Analyser\NodeScopeResolver->processCalledMethod(Object(PHPStan\Reflection\ResolvedMethodReflection))                
     #14 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(788): PHPStan\Analyser\NodeScopeResolver->processExprNode(Object(PhpParser\Node\Stmt\If_),                                         
     Object(PhpParser\Node\Expr\MethodCall), Object(PHPStan\Analyser\MutatingScope), Object(Closure), Object(PHPStan\Analyser\ExpressionContext))                                                                                       
     #15 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(422): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\If_),                                         
     Object(PHPStan\Analyser\MutatingScope), Object(Closure), Object(PHPStan\Analyser\StatementContext))                                                                                                                                
     #16 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(613): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\ClassMethod), Array,                         
     Object(PHPStan\Analyser\MutatingScope), Object(Closure), Object(PHPStan\Analyser\StatementContext))                                                                                                                                
     #17 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(422): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\ClassMethod),                                 
     Object(PHPStan\Analyser\MutatingScope), Object(PHPStan\Node\ClassStatementsGatherer), Object(PHPStan\Analyser\StatementContext))                                                                                                   
     #18 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(751): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\Class_), Array,                              
     Object(PHPStan\Analyser\MutatingScope), Object(PHPStan\Node\ClassStatementsGatherer), Object(PHPStan\Analyser\StatementContext))                                                                                                   
     #19 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(422): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Class_),                                      
     Object(PHPStan\Analyser\MutatingScope), Object(Closure), Object(PHPStan\Analyser\StatementContext))                                                                                                                                
     #20 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(721): PHPStan\Analyser\NodeScopeResolver->processStmtNodes(Object(PhpParser\Node\Stmt\Namespace_), Array,                          
     Object(PHPStan\Analyser\MutatingScope), Object(Closure), Object(PHPStan\Analyser\StatementContext))                                                                                                                                
     #21 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/NodeScopeResolver.php(390): PHPStan\Analyser\NodeScopeResolver->processStmtNode(Object(PhpParser\Node\Stmt\Namespace_),                                  
     Object(PHPStan\Analyser\MutatingScope), Object(Closure), Object(PHPStan\Analyser\StatementContext))                                                                                                                                
     #22 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Analyser/FileAnalyser.php(162): PHPStan\Analyser\NodeScopeResolver->processNodes(Array, Object(PHPStan\Analyser\MutatingScope), Object(Closure))                  
     #23 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Command/WorkerCommand.php(136): PHPStan\Analyser\FileAnalyser->analyseFile('/var/www/html/s...', Array, Object(PHPStan\Rules\LazyRegistry),                       
     Object(PHPStan\Collectors\Registry), NULL)                                                                                                                                                                                         
     #24 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/vendor/evenement/evenement/src/EventEmitterTrait.php(111): PHPStan\Command\WorkerCommand::PHPStan\Command\{closure}(Array)                                            
     #25 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/vendor/clue/ndjson-react/src/Decoder.php(117): _PHPStan_eb82cb2ad\Evenement\EventEmitter->emit('data', Array)                                                         
     #26 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/vendor/evenement/evenement/src/EventEmitterTrait.php(111): _PHPStan_eb82cb2ad\Clue\React\NDJson\Decoder->handleData(Array)                                            
     #27 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/vendor/react/stream/src/Util.php(62): _PHPStan_eb82cb2ad\Evenement\EventEmitter->emit('data', Array)                                                                  
     #28 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/vendor/evenement/evenement/src/EventEmitterTrait.php(111): _PHPStan_eb82cb2ad\React\Stream\Util::_PHPStan_eb82cb2ad\React\Stream\{closure}('{"action":"anal...')      
     #29 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/vendor/react/stream/src/DuplexResourceStream.php(168): _PHPStan_eb82cb2ad\Evenement\EventEmitter->emit('data', Array)                                                 
     #30 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/vendor/react/event-loop/src/StreamSelectLoop.php(201): _PHPStan_eb82cb2ad\React\Stream\DuplexResourceStream->handleData(Resource id #7705)                            
     #31 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/vendor/react/event-loop/src/StreamSelectLoop.php(173): _PHPStan_eb82cb2ad\React\EventLoop\StreamSelectLoop->waitForStreamActivity(NULL)                               
     #32 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/src/Command/WorkerCommand.php(96): _PHPStan_eb82cb2ad\React\EventLoop\StreamSelectLoop->run()                                                                         
     #33 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Command/Command.php(259): PHPStan\Command\WorkerCommand->execute(Object(_PHPStan_eb82cb2ad\Symfony\Component\Console\Input\ArgvInput),         
     Object(_PHPStan_eb82cb2ad\Symfony\Component\Console\Output\ConsoleOutput))                                                                                                                                                         
     #34 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(870):                                                                                                                          
     _PHPStan_eb82cb2ad\Symfony\Component\Console\Command\Command->run(Object(_PHPStan_eb82cb2ad\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_eb82cb2ad\Symfony\Component\Console\Output\ConsoleOutput))                 
     #35 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(261): _PHPStan_eb82cb2ad\Symfony\Component\Console\Application->doRunCommand(Object(PHPStan\Command\WorkerCommand),            
     Object(_PHPStan_eb82cb2ad\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_eb82cb2ad\Symfony\Component\Console\Output\ConsoleOutput))                                                                                   
     #36 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(157):                                                                                                                          
     _PHPStan_eb82cb2ad\Symfony\Component\Console\Application->doRun(Object(_PHPStan_eb82cb2ad\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_eb82cb2ad\Symfony\Component\Console\Output\ConsoleOutput))                   
     #37 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(114): _PHPStan_eb82cb2ad\Symfony\Component\Console\Application->run()                                                                                     
     #38 phar:///var/www/html/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(115): _PHPStan_eb82cb2ad\{closure}()                                                                                                                      
     #39 /var/www/html/vendor/phpstan/phpstan/phpstan(8): require('phar:///var/www...')                                                                                                                                                 
     #40 /var/www/html/vendor/bin/phpstan(119): include('/var/www/html/v...')                                                                                                                                                           
     #41 {main}

**Comment by SchmidtClaudia** [comment]
I created a pull request for the update see https://github.com/composer/pcre/pull/40
